AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample-Python-Telegram-Bot-AWS-Serverless

Parameters:
  TelegramBotToken:
    Type: String
    Default: ""
    NoEcho: true

Resources:
  ApiBotFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Timeout: 3
      Runtime: python3.11
      CodeUri: src/
      Handler: api.api_handler
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          SQS_QUEUE_URL: !GetAtt BotQueue.QueueUrl
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt BotQueue.QueueName

  SqsBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      Runtime: python3.11
      CodeUri: src/
      Handler: sqs.sqs_handler
      Events:
        BotSqs:
          Type: SQS
          Properties:
            BatchSize: 1
            Queue: !GetAtt BotQueue.Arn
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          SQS_QUEUE_URL: !GetAtt BotQueue.QueueUrl
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt BotQueue.QueueName

  BotQueue:
    Type: AWS::SQS::Queue

Outputs:
  TelegramApi:
    Value: !GetAtt ApiBotFunctionUrl.FunctionUrl
